Add settings to ignore errors on schema (#7)
## Changes
- introducing new settings:
- `pg_no_seqscan.ignored_schemas` to support a list of schemas to ignore
when checking seqscan
- `pg_no_seqscan.level` to define how to behave when a sequential scan
occurs
- refactoring to try to mutualize code and to simplify it
- some more tests

## Demo
```sql
select name, setting, short_desc, vartype, enumvals, boot_val from pg_settings where name LIKE 'pg_no_seqscan%';

             name              |            setting            |                   short_desc                   | vartype |     enumvals     |           boot_val            
-------------------------------+-------------------------------+------------------------------------------------+---------+------------------+-------------------------------
 pg_no_seqscan.ignored_schemas | pg_catalog,information_schema | List of schemas to ignore, separated by commas | string  |                  | pg_catalog,information_schema 
 pg_no_seqscan.level           | Error                         | Detection level for sequential scans           | enum    | {Off,Warn,Error} | Error                         

```

A seqscan on pg_catalog causes no error as it's ignored:
```sql
select * from pg_class;
```

A seqscan on public causes an error:
```sql
select * from foo;
ERROR:  A 'Sequential Scan' on foo has been detected.
  - Run an EXPLAIN on your query to check the query plan.
  - Make sure the query is compatible with the existing indexes.

Query: select * from foo;
```

But it can be ignored easily:
```sql
set pg_no_seqscan.ignored_schemas='pg_catalog,information_schema,public';
```


Also we can:
- pause the extension:
```sql
set pg_no_seqscan.level=off;
```
- set pg_no_seqscan to only log in PG (useless for CI and developers if
they don't check logs) when a seq scan occur:
```sql
set pg_no_seqscan.level=warn;
```
- set pg_no_seqscan to fail on each seq scan
```sql
set pg_no_seqscan.level=error;
```